"""Progressive baseball-IQ question banks used by the learning routes."""


LEVELS = (
    ("foundation", "Foundation", "Core reads and responsibilities"),
    ("competitive", "Competitive", "Multiple reads and game context"),
    ("advanced", "Advanced", "Technical execution and decision tradeoffs"),
)


def field(area, situation, outs, runners, runner_bases, play, question, answers, correct, explanation):
    return {
        "area": area, "situation": situation, "outs": outs, "runners": runners,
        "runner_bases": runner_bases, "play": play, "question": question,
        "answers": answers, "correct": correct, "explanation": explanation,
    }


FIELD_IQ_LEVELS = {
    "foundation": [
        field("Infield", "Halfway depth", 0, "3rd", ["third"], 0,
              "What does halfway depth ask an infielder to read before choosing home or first?",
              ["Only where the batter drops the bat", "The runner's break, ball speed, and whether a controlled out is available", "Whether the outfield is playing deep", "The catcher's throwing hand"], 1,
              "Halfway depth preserves two choices. Read the runner and the pace of the ball, then take the out the defense can execute."),
        field("Infield", "Double-play depth", 0, "1st", ["first"], 1,
              "Why do the shortstop and second baseman shade toward second before a likely ground ball?",
              ["To shorten the feed and arrive balanced for the turn", "To prevent every hit through the middle", "To make the first baseman cover second", "To allow both players to charge the hitter"], 0,
              "Double-play depth shortens the first exchange while keeping each middle infielder ready to cover or feed."),
        field("Infield", "Bunt rotation", 0, "1st", ["first"], 2,
              "Both corner infielders charge a shown bunt. What must the middle infielders do immediately?",
              ["Hold their normal depth until the ball is fielded", "Both cover second", "Replace the vacated bases according to the team's bunt call", "Follow the runner toward home"], 2,
              "A bunt defense works only when teammates replace the bases vacated by charging defenders."),
        field("Outfield", "Relay to third", 1, "1st", ["first"], 3,
              "A single reaches right field and the runner attacks third. What makes the cutoff effective?",
              ["Standing directly on second base", "Aligning the ball with third, showing a target, and listening for cut or through", "Catching every throw even when it is on line", "Moving toward home before the throw"], 1,
              "The cutoff aligns the throw with its target and reacts to the receiving infielder's communication."),
        field("Outfield", "Tag-up throw", 1, "3rd", ["third"], 4,
              "After catching a medium-depth fly ball, what produces the quickest accurate throw home?",
              ["Drifting backward through the catch", "Catching flat-footed and crow-hopping twice", "Setting up behind the ball and carrying momentum through the catch", "Throwing before locating the cutoff"], 2,
              "Getting behind the ball lets the outfielder catch while moving toward the target and reduces transfer time."),
        field("Catching", "Ball in the dirt", 2, "3rd", ["third"], 5,
              "With a runner on third, when should a catcher prioritize blocking over receiving?",
              ["When the pitch trajectory is likely to reach the dirt or skip", "Only after the ball passes the plate", "Whenever the count has two strikes", "Only when the pitcher calls a breaking ball"], 0,
              "The catcher reads trajectory early and gets the body behind a pitch that may reach the dirt."),
        field("Baserunning", "Secondary lead", 1, "1st", ["first"], 1,
              "What makes a secondary lead useful without turning it into an easy pickoff?",
              ["Crossing the feet as the pitch reaches the plate", "Moving on the pitch, staying balanced, and returning quickly when the ball is secured", "Leaving before the pitcher commits home", "Watching only the third-base coach"], 1,
              "A controlled secondary lead creates distance while keeping the runner balanced enough to read and return."),
        field("Hitting", "Runner at third", 1, "3rd", ["third"], 0,
              "The infield is back with one out and a runner on third. What is the hitter's best plan?",
              ["Expand the zone to guarantee contact", "Look for a pitch that can be driven on the ground or on a controlled line", "Take until two strikes regardless of location", "Try to pull every pitch in the air"], 1,
              "The hitter should hunt a pitch that can be controlled, not trade away the strike zone just to touch the ball."),
        field("Pitching", "Back up the play", 1, "2nd", ["second"], 7,
              "A base hit goes to center and the runner is sent home. Where does the pitcher belong?",
              ["At the front edge of the mound", "Behind the plate in line with the developing throw", "Covering first base", "Beside the cutoff"], 1,
              "The pitcher moves behind home far enough to contain an overthrow without interfering with the play."),
        field("Team Defense", "Rundown", 1, "1st & 2nd", ["first", "second"], 8,
              "What is the cleanest way to finish a rundown?",
              ["Protect the lead base, run the runner hard, and use as few throws as possible", "Throw immediately every time the runner turns", "Have every infielder enter the baseline", "Protect the trailing base even if the lead runner advances"], 0,
              "The defense protects the lead base and closes distance so the next throw can produce a tag."),
    ],
    "competitive": [
        field("Infield", "Depth decision", 1, "3rd", ["third"], 0,
              "Tie game in the fifth, one out, runner on third. Which factor most strongly separates playing in from halfway?",
              ["The batter's uniform number", "Whether preventing the run outweighs the lost range and reliable out at first", "Which dugout is louder", "Whether the pitcher throws right-handed"], 1,
              "Depth is a run-versus-out tradeoff shaped by score, inning, runner, hitter, and team plan."),
        field("Infield", "Double-play feed", 0, "1st", ["first"], 1,
              "The second baseman fields a hard ground ball several steps to the glove side. What feed best protects the turn?",
              ["A controlled underhand or short-arm feed that leads the shortstop through the bag", "A maximum-effort throw at the shortstop's chest", "A high arc that gives the runner time to slide", "A backhand flip regardless of body position"], 0,
              "The feed should match distance and momentum while leading the pivot player away from the runner's path."),
        field("Catching", "First-and-third", 1, "1st & 3rd", ["first", "third"], 9,
              "Before a likely steal of second with a runner on third, what is the catcher's most important responsibility?",
              ["Decide after releasing the throw", "Confirm the team's call, identify who protects home, and communicate the throw or fake", "Always throw through to second", "Move the third baseman to first"], 1,
              "First-and-third defense must be called before the pitch so every defender knows the priority and coverage."),
        field("Outfield", "Do-or-die approach", 2, "2nd", ["second"], 4,
              "The tying runner rounds third on a clean single with two outs. When is a do-or-die pickup justified?",
              ["When the outfielder has a realistic play at home and no safer run matters behind it", "On every ground ball with two outs", "Only when the ball is hit directly at the outfielder", "Whenever the cutoff asks for the ball"], 0,
              "A do-or-die approach trades security for release time and is justified when the game situation demands the play."),
        field("Catching", "Blocking angle", 1, "2nd & 3rd", ["second", "third"], 5,
              "A breaking ball is designed below the zone with runners aboard. Where should the catcher center the block?",
              ["Where the ball is expected to rebound after its downward angle", "Directly behind the umpire", "Toward the throwing-hand side regardless of pitch shape", "On the center of home plate every time"], 0,
              "Good blockers anticipate pitch angle and move the chest behind the likely rebound path."),
        field("Baserunning", "Dirt-ball read", 1, "1st", ["first"], 5,
              "What three cues should a runner combine before advancing on a pitch in the dirt?",
              ["Pitch location, distance of the rebound, and the catcher's recovery path", "Only the coach's voice", "The pitcher's velocity, inning, and batting order", "The umpire's position, bat angle, and scoreboard"], 0,
              "The runner reads where the ball finishes, how quickly the catcher can recover, and whether the next base is available."),
        field("Hitting", "Two-strike plan", 2, "2nd", ["second"], 9,
              "A pitcher has expanded away twice with two strikes. What is the best adjustment?",
              ["Cover the outer lane longer while still protecting the inner edge", "Move closer and commit earlier to every pitch", "Eliminate the opposite field", "Swing at anything the catcher can reach"], 0,
              "A two-strike adjustment can protect the observed lane without abandoning the rest of the competitive zone."),
        field("Pitching", "Bunt PFP", 0, "1st & 2nd", ["first", "second"], 2,
              "On a bunt back to the pitcher with a force available at third, what determines whether to take the lead out?",
              ["The dugout's reaction", "A clean field, a pre-pitch read, and a throw that can beat the runner", "Whether the batter is left-handed", "The catcher's mask location"], 1,
              "The pitcher checks the lead play before the pitch, but takes it only when the field-and-throw sequence is under control."),
        field("Rules", "Force third out", 2, "1st & 3rd", ["first", "third"], 1,
              "The runner from third touches home before a force out is recorded at second for the third out. Does the run count?",
              ["Yes, because the runner touched home first", "No, a run cannot score when the third out is a force out", "Yes, if the batter reached first", "Only if the defense appeals home"], 1,
              "No run scores when the third out is recorded on a force play, regardless of when home was touched."),
        field("Team Defense", "Relay trailer", 2, "1st", ["first"], 3,
              "Why should a second infielder trail a long relay instead of standing beside the primary relay?",
              ["To create depth for an offline throw and continue the play if the first relay cannot handle it", "To call time immediately", "To cover home plate", "To distract the runner"], 0,
              "A trailer provides depth, adjusts for an offline throw, and keeps the relay moving."),
    ],
    "advanced": [
        field("Infield", "Contact play", 1, "3rd", ["third"], 0,
              "On a contact play, the runner breaks from third on a downward ball. What must the drawn-in infielder process before releasing home?",
              ["Only whether the ball is fair", "Ball speed, runner jump, fielding momentum, and the catcher's lane", "The batter's previous result only", "Whether first base is occupied"], 1,
              "The home decision is a timed calculation. A late or off-balance throw can sacrifice both the run and the out."),
        field("Infield", "Slow-developing turn", 0, "1st", ["first"], 1,
              "A backhand ground ball takes the shortstop away from second. What is the advanced double-play priority?",
              ["Force a cross-body flip no matter the angle", "Secure the lead force only if the feed remains controlled; otherwise record the sure out at first", "Hold the ball to preserve the double play", "Throw directly to third"], 1,
              "Advanced decision-making recognizes when forcing a low-percentage feed turns one available out into none."),
        field("Outfield", "Positioning model", 1, "2nd", ["second"], 4,
              "Which information should change an outfielder's starting depth and lateral shade before the pitch?",
              ["Hitter contact profile, pitch plan, wind, score, and the consequence of a ball over the head", "Only the hitter's handedness", "Only the dimensions printed on the fence", "The on-deck hitter's position"], 0,
              "Advanced positioning combines hitter and pitch tendencies with environmental and game-state risk."),
        field("Catching", "Receive or block", 2, "3rd", ["third"], 5,
              "With two strikes and a runner on third, how should a catcher handle a borderline breaking ball finishing at the bottom edge?",
              ["Commit to receiving even after reading a likely bounce", "Read trajectory first: receive a catchable strike, but beat a likely dirt ball to the spot", "Drop immediately before release", "Reach across the body so the glove stays visible"], 1,
              "The catcher must preserve the strike when catchable without gambling on a pitch that is likely to reach the dirt."),
        field("Baserunning", "Line-drive freeze", 0, "2nd", ["second"], 7,
              "On a low line drive with no outs, what is the runner at second reading before choosing freeze, return, or advance?",
              ["Fielder depth, ball trajectory, and whether the ball can be caught in front", "Only the third-base coach", "Whether the hitter leaves the box", "The catcher's setup"], 0,
              "The runner gains information before committing so a catch does not become an avoidable double play."),
        field("Hitting", "Pattern recognition", 2, "1st & 2nd", ["first", "second"], 9,
              "The pitcher has used elevated fastballs ahead and changeups below when even. What is the strongest two-strike plan?",
              ["Protect the upper fastball lane early while tracking spin and depth long enough to reject the changeup below", "Guess changeup and ignore the fastball", "Cover every pitcher's pitch by widening the strike zone", "Start the swing before release"], 0,
              "The hitter uses the observed sequence to prioritize a lane while maintaining decision time on the secondary pitch."),
        field("Pitching", "Control the running game", 1, "1st", ["first"], 9,
              "How can a pitcher disrupt a fast runner without degrading pitch execution?",
              ["Use varied legal holds and looks while keeping the delivery repeatable", "Slide-step every pitch regardless of command", "Throw over until the runner stops leading", "Ignore the runner and rush the plate"], 0,
              "Variation changes the runner's timing; repeatable mechanics keep the pitch quality intact."),
        field("Team Defense", "Cut decision", 1, "1st & 2nd", ["first", "second"], 3,
              "A throw from right field is online to third while the batter-runner takes second. When should the cutoff cut it?",
              ["Whenever the ball can be caught", "When the defense no longer has a realistic play at third and can retire or stop the trail runner", "Only after the runner reaches third", "Never if the throw is online"], 1,
              "The cutoff reads the lead play and redirects the ball when controlling the trail runner creates the better outcome."),
        field("Rules", "Infield fly", 1, "1st & 2nd", ["first", "second"], 6,
              "An infield fly is declared and the ball drops untouched in fair territory. What remains true?",
              ["The batter is out, the ball stays live, and runners advance at their own risk", "The ball is dead immediately", "All runners receive one base", "The batter may run because nobody caught it"], 0,
              "The infield-fly call removes the force created by the batter-runner, but the ball remains live."),
        field("Team Defense", "Winning run at plate", 2, "2nd", ["second"], 4,
              "Bottom of the last inning, tie game, two outs, runner on second. How should the outfield and relay priorities change?",
              ["Protect against the run scoring, attack the ball, and align the relay to home with no concern for the batter-runner after the winning run", "Play extra deep to prevent every double", "Throw to second to hold the batter-runner", "Concede the run to prevent an extra-base hit"], 0,
              "When one run ends the game, positioning and execution prioritize the only runner who can decide it."),
    ],
}


def pitch(title, category, count, hitter, pitch_code, zone_x, zone_y, question, answers, correct, explanation):
    return {
        "title": title, "category": category, "count": count, "hitter": hitter,
        "pitch": pitch_code, "zone_x": zone_x, "zone_y": zone_y,
        "question": question, "answers": answers, "correct": correct,
        "explanation": explanation,
    }


PITCH_PLAN_LEVELS = {
    "foundation": [
        pitch("Establish a lane", "COMMAND", "0-0", "RHH", "FB", 43, 58, "Without a hitter report, what is the strongest first-pitch plan?", ["Use the pitch and lane the pitcher commands best", "Aim for a chase before showing a strike", "Select the pitch with the most movement even without command", "Change the delivery to create surprise"], 0, "A controlled strike in a planned lane creates information and puts the pitcher in a better count."),
        pitch("Competitive chase", "COUNT LEVERAGE", "0-2", "LHH", "SL", 75, 74, "What separates a useful chase pitch from a noncompetitive waste pitch?", ["It is always a breaking ball", "It looks like a strike long enough to force a decision, then finishes outside the zone", "It begins outside the hitter's visual window", "It must bounce before the plate"], 1, "A chase pitch earns commitment because its early flight resembles a strike."),
        pitch("Hitter's count", "DAMAGE CONTROL", "2-0", "RHH", "FB", 36, 55, "What is the best 2-0 fastball target?", ["The smallest corner of the plate", "A commanded lane away from the heart while still producing a strike", "Above the hands regardless of command", "The same exact spot used on 0-0"], 1, "The pitcher needs a strike but should not surrender the highest-damage part of the zone."),
        pitch("Changeup conviction", "PITCH SHAPE", "1-1", "LHH", "CH", 62, 69, "Which cue makes a changeup play most effectively off the fastball?", ["Reduced arm speed", "Matching intent and early trajectory before late speed separation", "A visibly shorter stride", "Starting the pitch outside the tunnel"], 1, "Fastball intent and similar early flight delay recognition while speed and movement separate late."),
        pitch("Ground-ball lane", "CONTACT MANAGEMENT", "0-1", "RHH", "SNK", 45, 73, "With a runner on first, why target a sinker at the lower third rather than below the dirt?", ["It creates a competitive strike lane with a better chance of ground contact", "It guarantees a double play", "It prevents the runner from stealing", "It removes the need for infield positioning"], 0, "The target balances strike probability with the desired contact shape."),
        pitch("Reset at 3-0", "COUNT AWARENESS", "3-0", "RHH", "FB", 50, 55, "What should the pitcher simplify on 3-0?", ["Grip pressure and tempo while using the most repeatable strike pitch", "The target by aiming at the entire plate", "The delivery by rushing to home", "Pitch selection by trying an untested offering"], 0, "A repeatable delivery and trusted pitch give the best chance to return to a competitive count."),
        pitch("Two-strike weapon", "EXECUTION", "1-2", "RHH", "CH", 66, 76, "Which two-strike call is most defensible?", ["The pitch with the largest theoretical movement", "A weapon the pitcher can execute that matches the hitter's previous reactions", "Any pitch outside the zone", "The catcher's favorite pitch regardless of today's command"], 1, "The best call combines execution confidence with evidence from the hitter's swings and takes."),
        pitch("Avoid the heart", "LOCATION", "3-1", "LHH", "FB", 33, 52, "Why choose a defined lane instead of simply trying to throw a strike on 3-1?", ["A committed hitter can punish a vague middle target", "The pitch cannot be called a ball", "Only outside pitches count as strikes", "Velocity matters less than the count"], 0, "A defined, commandable lane protects against a middle-middle miss while honoring the count."),
        pitch("Runner at third", "GAME STATE", "1-0", "RHH", "FB", 46, 70, "With fewer than two outs and a runner on third, what does a lower target try to manage?", ["The possibility of elevated contact while keeping the pitch competitive", "The runner's legal lead", "The catcher's throwing time", "The umpire's strike mechanic"], 0, "A lower competitive lane can reduce easy air contact without pretending any pitch guarantees a ground ball."),
        pitch("Sequence with purpose", "SEQUENCING", "2-2", "LHH", "CB", 32, 75, "After two firm pitches at the upper arm-side lane, why can a breaking ball below the opposite edge work?", ["It changes speed, eye level, and movement direction", "Breaking balls are always best on 2-2", "The hitter is required to swing", "The pitch starts outside the visual tunnel"], 0, "The sequence creates multiple late adjustments while preserving a believable early path."),
    ],
    "competitive": [
        pitch("Read the take", "HITTER INFORMATION", "1-0", "RHH", "FB", 68, 48, "The hitter takes a well-located outer fastball without tracking it closely. What is the most useful inference?", ["The hitter can never cover away", "The outer lane may remain available, but the next pitch must still account for count and expected adjustment", "Repeat the identical pitch until contact", "The hitter is guessing breaking ball with certainty"], 1, "A take is evidence, not proof. Use it to shape the plan while anticipating adjustment."),
        pitch("Change eye level", "SEQUENCING", "0-2", "RHH", "FB", 47, 24, "After a slider below the zone produced a defensive check, what is the purpose of a controlled fastball above the hands?", ["To change the hitter's visual window and challenge a swing path moving down", "To guarantee a strikeout", "To make the next slider spin more", "To avoid using the lower half again"], 0, "Changing eye level can disrupt a hitter protecting down, provided the fastball is commanded above rather than in the damage lane."),
        pitch("Tunnel decision", "PITCH DESIGN", "1-1", "LHH", "CH", 68, 67, "What makes a fastball-changeup tunnel useful against an opposite-handed hitter?", ["Both pitches finish in the same exact location", "Similar release and early flight force a later decision before speed and fade separate", "The changeup uses a slower arm", "The fastball must be thrown inside"], 1, "The tunnel delays recognition without requiring identical final locations."),
        pitch("Miss pattern", "SELF-SCOUT", "2-1", "RHH", "SL", 72, 69, "The slider has repeatedly backed up arm-side. What is the best in-game response?", ["Call it more often until it improves", "Adjust the plan toward pitches currently executing and use the slider only with a safer target or after a mechanical cue", "Aim farther glove-side without discussing the miss", "Increase effort to create more break"], 1, "A useful plan responds to today's miss pattern instead of relying on intended pitch shape."),
        pitch("Steal count", "RUNNING GAME", "2-1", "LHH", "FB", 40, 55, "A fast runner has timed the pitcher's longest hold. What adjustment protects both the plate and running game?", ["Rush every delivery", "Vary legal holds and looks while selecting a pitch the catcher can receive and throw from", "Throw over on every attempt", "Use only breaking balls"], 1, "Timing variation disrupts the runner while the pitch call supports the catcher's exchange."),
        pitch("Weak-contact plan", "CONTACT MANAGEMENT", "0-0", "LHH", "SNK", 63, 72, "A pull-oriented left-handed hitter rolls over sinkers below the hands. Which plan best uses that information?", ["Start a sinker in a lane that can finish below the hands without leaking middle", "Throw every sinker below the zone", "Abandon fastballs entirely", "Aim directly at the back foot"], 0, "Use the known contact tendency with a target that still protects against a middle miss."),
        pitch("Set up the finisher", "SEQUENCING", "1-2", "RHH", "CB", 30, 76, "Why might a pitcher show a fastball just off the upper lane before returning to a curveball below?", ["To widen the hitter's protected vertical window", "Because every curveball requires a high fastball first", "To make the curveball faster", "To reset the ball-strike count"], 0, "The show pitch forces the hitter to protect height, increasing the adjustment required for depth."),
        pitch("Open-base leverage", "GAME STATE", "1-1", "RHH", "SL", 76, 63, "First base is open with two outs and the best hitter is at the plate. What changes in the plan?", ["Every pitch must be outside", "The battery can avoid the hitter's strongest zone and accept a walk rather than concede damage", "The pitcher should throw only strikes", "The runner at second no longer matters"], 1, "An open base changes the cost of a walk and allows the battery to be less predictable in the strike zone."),
        pitch("Recover after miss", "COMPOSURE", "3-1", "LHH", "FB", 36, 54, "After missing arm-side twice, what is the most useful adjustment before the 3-1 pitch?", ["Add effort", "Reset the breath, identify the miss, and commit to a broad lane with the most repeatable pitch", "Aim at the opposite batter's box", "Shorten the follow-through"], 1, "A specific reset is more actionable than compensating wildly for the previous miss."),
        pitch("Catcher-pitcher feedback", "BETWEEN INNINGS", "0-0", "RHH", "CH", 65, 70, "What is the most technical useful between-inning conversation?", ["Which pitches looked good", "Which shapes were commanded, how hitters reacted, and where the miss pattern is occurring", "Whether the umpire likes the catcher", "Which pitch should be thrown every at-bat"], 1, "Execution, reaction, and miss-pattern data produce an adaptable plan."),
    ],
    "advanced": [
        pitch("Attack the swing plane", "PITCH DESIGN", "1-2", "RHH", "FB", 48, 23, "A hitter's barrel works steeply down to low pitches and is late above the belt. Which fastball plan best exploits that path?", ["Elevate above the barrel with enough margin to avoid a middle-height miss", "Throw at the top edge regardless of fastball life", "Locate every fastball below the knees", "Reduce velocity to create timing"], 0, "The plan attacks the observed swing plane while accounting for the danger of a miss that falls into the heart."),
        pitch("Shape pairing", "TUNNELING", "1-1", "LHH", "SL", 31, 63, "Which slider pairs best with a glove-side fastball from the same release?", ["One that shares early trajectory before separating below and glove-side", "One released from a visibly lower slot", "One that starts outside the tunnel", "One thrown with reduced intent"], 0, "Release and early-flight overlap delay recognition; late shape separation creates the decision problem."),
        pitch("Third-time adjustment", "HITTER ADJUSTMENT", "0-0", "RHH", "CH", 66, 67, "The hitter has taken first-pitch fastballs twice and was early on changeups later. What is a strong third-at-bat adjustment?", ["Repeat the first-pitch fastball because it worked before", "Consider a first-pitch changeup in a strike lane while preserving fastball arm speed", "Throw a changeup below the zone for ball one", "Eliminate the fastball from the at-bat"], 1, "The sequence uses the hitter's established timing expectation without wasting the count advantage."),
        pitch("Count-dependent target", "RISK MANAGEMENT", "3-2", "LHH", "FB", 39, 48, "With two outs, first base open, and a dangerous hitter, how should the 3-2 target differ from a bases-loaded 3-2 target?", ["It should not differ", "With first open the pitcher can avoid the damage lane; bases loaded requires a more strike-probable target", "Bases loaded allows a chase pitch", "First open requires a middle strike"], 1, "The cost of a walk changes dramatically with base state, so the target's risk profile should change too."),
        pitch("Vertical approach angle", "FASTBALL SHAPE", "0-2", "RHH", "FB", 51, 25, "Why can a fastball with strong carry play above the zone even without elite velocity?", ["Its flatter approach can keep it above an uppercut barrel longer than the hitter expects", "It rises after crossing the plate", "Velocity has no effect on timing", "The umpire expands the zone upward"], 0, "A flatter vertical approach changes where the ball intersects the swing plane and can create misses above the barrel."),
        pitch("Protect the miss", "TARGET DESIGN", "2-2", "LHH", "SL", 77, 69, "A back-foot slider is called to an opposite-handed hitter, but the pitcher's common miss is arm-side and elevated. What is the main risk?", ["The miss can leak into the hitter's pull-side damage lane", "The pitch will always hit the batter", "The slider will become a changeup", "The catcher cannot block it"], 0, "Advanced target selection evaluates not only the intended pitch but where the pitcher's common miss finishes."),
        pitch("Sequence without predictability", "GAME THEORY", "1-2", "RHH", "CH", 69, 75, "The scouting report says the hitter chases changeups below, but the battery has used that finish twice. What is the best reasoning?", ["Throw it again because reports never change", "Balance the hitter's weakness against the likelihood of recognition and choose the best executable counter", "Avoid the changeup for the rest of the game", "Throw the least-used pitch regardless of quality"], 1, "Good sequencing weighs prior probability, in-game evidence, predictability, and execution."),
        pitch("Pitch clock routine", "TEMPO", "2-0", "LHH", "FB", 35, 54, "How should a pitcher preserve decision quality when the clock is shortening after a disengagement?", ["Pre-plan the next pitch and target with the catcher, then use the normal compact reset", "Rush the arm to beat the clock", "Skip the target and throw to the glove", "Automatically step off again"], 0, "A pre-planned pitch and compact routine protect mechanics and decision quality under time pressure."),
        pitch("Contact-quality tradeoff", "RUN EXPECTANCY", "0-0", "RHH", "SNK", 44, 71, "Runner on first, no outs, elite power hitter. Why might inducing a ground ball still not justify living in the hitter's strongest low lane?", ["Ground balls can never become hits", "The double-play benefit must be weighed against the hitter's damage on that location and the pitcher's ability to miss safely", "A runner on first removes home-run risk", "Sinkers are ineffective against power hitters"], 1, "The plan balances possible double-play value against location-specific damage and miss consequences."),
        pitch("Finish the at-bat", "EXECUTION", "3-2", "RHH", "CB", 32, 67, "A curveball has landed for strikes all day and the hitter has stopped offering at chase curves. What supports using it on 3-2?", ["Trusting the strike version with conviction because the hitter's take pattern and today's command support it", "Breaking balls cannot be thrown on full counts", "Aiming below the zone and hoping for a call", "Slowing the arm to guarantee a strike"], 0, "The call is supported by demonstrated command and hitter behavior, not by pitch-type convention."),
    ],
}


for level, questions in FIELD_IQ_LEVELS.items():
    for question in questions:
        question["level"] = level

for level, questions in PITCH_PLAN_LEVELS.items():
    for question in questions:
        question["level"] = level
