PRACTICE_DRILLS = [
    ("Throwing", "01. Four Steps to Throwing", "Grip, separate, step to the target, and finish through the throw."),
    ("Fielding", "02. Glove and Throwing Hand Out When Down and Ready", "Present both hands out front from a balanced ready position."),
    ("Fielding", "03. Rocker Footwork for Ground Balls", "Rock forward, field out front, and carry momentum toward the target."),
    ("Fielding", "04. Bring the Ball to the Chest", "Funnel the fielded ball to the chest and find a four-seam grip."),
    ("Fielding", "05. Create Angles on Ground Balls", "Move early and round the ball so the feet work toward the throw."),
    ("Fielding", "06. Backhand Progression", "Progress from stationary backhands to moving backhands and throws."),
    ("Fielding", "07. One-Hand Fielding", "Use the glove hand independently while keeping the throwing hand free."),
    ("Throwing", "08. Off-Balance Throwing: Three-Step Progression", "Secure the ball, replace the feet, and throw from a stable finish."),
    ("Fielding", "09. Self-Toss Pop Flies", "Create a high toss, move underneath it, call it, and catch above the forehead."),
    ("Fielding", "10. Partner Pop Flies", "Communicate, move behind the ball, and transition from catch to throw."),
    ("Throwing", "11. Long-Toss Routine", "Build distance gradually with clean mechanics, then work back in with firm throws."),
    ("Throwing", "12. Firm Throws to a Target", "Throw with controlled intent and measure accurate hits instead of maximum effort."),
    ("Fielding", "13. Ground-Up Fielding: Four-Step Progression", "Build from knees to a complete approach, field, transfer, and throw."),
    ("Throwing", "14. Thumbs-Down Separation Throws", "Separate smoothly with thumbs down while keeping the front shoulder on target."),
    ("Catching", "15. Catcher Blocking", "Replace the feet with the knees, keep the chest forward, and deaden the ball."),
    ("Catching", "16. Catcher Transfer Drill", "Receive quietly, exchange near the chest, and find a four-seam grip."),
    ("Catching", "17. Catcher Ground-Up Progression", "Build receiving, transfer, footwork, and throwing mechanics in four stages."),
    ("Catching", "18. Catcher Elbow Out and Up", "Set a natural throwing slot and finish the throw through the base."),
    ("Catching", "19. Catcher Chasing Passed Balls", "Find the quickest route, recover under control, and feed the pitcher at home."),
    ("Catching", "20. Rapid Receiving", "Receive quick tosses at changing locations with quiet glove movement."),
    ("Baserunning", "21. Lead-Off Fundamentals", "Build a controlled lead while staying ready to advance or return."),
    ("Baserunning", "22. Stealing on the Pitcher's Move", "Read the pitcher's first committed move and accelerate with a clean crossover."),
    ("Baserunning", "23. Return to Base With Chest Outward", "Return quickly while keeping the chest open toward the field and away from the tag lane."),
    ("Baserunning", "24. Delayed Steals", "Read the catcher's attention and break after the defense creates an opening."),
    ("Baserunning", "25. Steal Second When It Is Uncovered", "Recognize when neither middle infielder covers and advance only on the team call."),
    ("Batting", "26. Bunting Fundamentals", "Set the barrel at the top of the zone and use the knees to direct the ball."),
    ("Batting", "27. Inward Pressure on the Balls of the Feet", "Create an athletic base with pressure inside both feet throughout the load."),
    ("Batting", "28. Hitting Balance", "Keep the head centered and land the stride softly under control."),
    ("Batting", "29. Drive the Hip", "Load the rear hip and drive it through after the front side firms."),
    ("Batting", "30. Drive Consistently Through the Middle", "Keep the barrel through the center lane and finish without pulling off."),
    ("Batting", "31. Maintain Space Between the Hands and Chest", "Preserve the hand gap during the load and turn without collapsing."),
    ("Batting", "32. Drive the Hands Along the White Line", "Use a visual line toward the pitcher to train a direct hand path."),
    ("Batting", "33. Low, Consistent Stride", "Move the front foot low and land softly in a repeatable location."),
    ("Batting", "34. Keep the Front Shoulder Inward", "Stay closed through foot strike and rotate only after tracking the pitch."),
    ("Batting", "35. Keep the Hands Up Near the Chest", "Start relaxed and return the hands to a strong launch position."),
    ("Batting", "36. Hands Near the Chin and Barrel High for High Pitches", "Use the tall barrel position only after identifying a high strike."),
    ("Fielding", "37. Catch Fly Balls While Staying Low and Athletic", "Settle the feet before the catch and remain ready to throw."),
    ("Fielding", "38. Drop the Correct Shoulder When Tracking Fly Balls", "Drop the shoulder on the route side and use a clean first step."),
    ("Pitching", "39. Pitching Mechanics: Balance, Sit, Drive", "Balance over the back leg, sit into the hip, and drive toward the plate."),
    ("Pitching", "40. Keep It Simple", "Repeat a compact delivery with one clear cue at a time."),
    ("Pitching", "41. Drive Through the Heel", "Load into the back hip and move toward the plate through the heel."),
    ("Pitching", "42. Low, Long Pitching Stride", "Move down the mound with a low, controlled stride and balanced landing."),
]

